### PR TITLE
Ensure everything compiles individually & sort includes

### PR DESCRIPTION
**Pull request by popoffka**
A lot of the files in our codebase don't properly include all of their dependencies. A common example of this is a situation like this: `a.hpp` uses `std::vector` in a definition, so it would need to have a line saying `#include <vector>`, but it doesn't. `a.hpp` does not include `vector` neither directly nor indirectly, but whenever `a.hpp` is included from another file, that file just happens to include `vector` beforehand.

The result is that, while running `make` succeeds, the code is quite brittle. The fact that `vector` is always included before `a.hpp` (in *current* uses of the library) might be quite accidental, and users might in theory want to use `a.hpp` in another file that doesn't need `vector` itself. Besides, it's just not particularly good style to not include our dependencies explicitly.

Luckily, this specific problem is easy to detect: if you were to try to compile `a.hpp` on its own, compilation would not succeed. I wrote a script (`try_compiling.py` in `libsnark-tooling`) that tries to individually compile every single file (`*.hpp` or `*.cpp`) in libff and reports whether it succeeds.

I then went through the report and fixed every single compilation error --- almost all of them were because of missing includes.

This does not resolve all possible include-related problems: in the situation above, perhaps `a.hpp` actually has a line saying `#include <libff/b.hpp>`, and `b.hpp` includes `vector` --- then `a.hpp` compiles just fine, but is still not explicitly listing all of its dependencies (perhaps `b.hpp`'s dependencies will change in the future, and it will no longer require `vector` --- then we'll get a broken `a.hpp` despite no real changes inside it). But I think this is a much smaller problem, and it's also much harder to even detect automatically, so for now I'm submitting just these changes.

While I was at it, I also sorted the #include directives in every file --- they are now grouped into three groups (standard library, external libraries, and libff) and sorted lexicographically within each group. This was done using `fix-includes.py` in `libsnark-tooling`.

Another minor change I made is that `libff/common/default_types/ec_pp.hpp` will now refuse to compile (with a helpful error message) if none of the `CURVE_*` symbols are defined, because that file is always included with the expectation that it will define `default_ec_pp`.

### CODE REVIEW

**Comment by tromer** [comment]
Looks great, and indeed needed. Let's merge.
